#cloud-config
users: # Liste der Users
  - name: ubuntu # Name des ersten Users
    sudo: ALL=(ALL) NOPASSWD:ALL # Rechte alle Commands auszufuehren die User ohne Passwort ausfuehren koennen
    groups: users, admin # Gruppen zu denen der User zugehoert
    home: /home/ubuntu # Home Verzeichnis des Users
    shell: /bin/bash # Home shell des Users
    lock_passwd: false # Erlaubnis fuer den User mit einem Passwort einzuloggen
    plain_text_passwd: 'password' # Passwort des Users
ssh_pwauth: true # Man braucht eine Autorisierung durch ein Passwort
disable_root: false # Man kann nicht Admin sein
packages: # verschieden Zusatzinhalte
  - mariadb-server
  - adminer
runcmd:
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;" 
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb.service
write_files:
  - path: /var/www/html/info.php
    content: |
      <?php
      // Show all information, defaults to INFO_ALL
      phpinfo();
      ?>
    permissions: "0644"
  - path: /var/www/html/db.php
    content: |
      <?php
      //database
      $servername = "172.23.98.36";
      $username = "admin";
      $password = "password";
      $dbname = "mysql";

      // Create connection
      $conn = new mysqli($servername, $username, $password, $dbname);
      // Check connection
      if ($conn->connect_error) {
              die("Connection failed: " . $conn->connect_error);
      }

      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while($row = $result->fetch_assoc()){
              echo($row["Host"] . " / " . $row["User"] . "<br />");
      }
      //var_dump($result);
      ?>
    permissions: "0644"
